### ISSUE TITLE
Onelo architecture

### ISSUE THREAD

**Issue by arnau** [onelocom/onelo#16]
~deleted content~

Updated content here: https://github.com/onelocom/onelo/blob/architecture/docs/architecture/README.md

**Comment by arnau** [comment]
![image](https://user-images.githubusercontent.com/33837/93665741-ec8a7700-fa70-11ea-9edf-5c46db4a9ccf.png)

**Comment by israelfenor** [comment]
Should content_type have one field more to store the name of the content type? @arnau

**Comment by arnau** [comment]
In `sourcing_phase` I defined it like this:

```sql
-- The set of known content types.
CREATE TABLE IF NOT EXISTS content_type (
    id text NOT NULL PRIMARY KEY,
    -- Not all possible media types are registered but when they are, they
    -- must match the IANA [registry](https://www.iana.org/assignments/media-types/media-types.xhtml)
    media_type text
);
```

But happy to adapt to reflect your struct

**Comment by arnau** [comment]
I created an `architecture` label so, instead of having this long-lived issue for any kind of discussion around architecture, we can have many specialised ones. E.g. #30
